package bpms.new_formmodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NestedDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String stringTextBox;

	private int intIntegerBox;

	private java.util.List<java.lang.String> stringMultipleSelector;

	private java.util.List<java.lang.String> stringMultipleInput;

	private java.lang.String stringTextArea;

	private java.lang.Integer integerRadioGroup;

	private java.lang.String stringListBox;

	private java.lang.Double doubleSlider;

	private java.lang.Double doubleDecimalBox;

	private java.lang.Boolean booleanCheckBox;

	private java.util.Date dateDatePicker;

	public NestedDataObject() {
	}

	public java.lang.String getStringTextBox() {
		return this.stringTextBox;
	}

	public void setStringTextBox(java.lang.String stringTextBox) {
		this.stringTextBox = stringTextBox;
	}

	public int getIntIntegerBox() {
		return this.intIntegerBox;
	}

	public void setIntIntegerBox(int intIntegerBox) {
		this.intIntegerBox = intIntegerBox;
	}

	public java.util.List<java.lang.String> getStringMultipleSelector() {
		return this.stringMultipleSelector;
	}

	public void setStringMultipleSelector(
			java.util.List<java.lang.String> stringMultipleSelector) {
		this.stringMultipleSelector = stringMultipleSelector;
	}

	public java.util.List<java.lang.String> getStringMultipleInput() {
		return this.stringMultipleInput;
	}

	public void setStringMultipleInput(
			java.util.List<java.lang.String> stringMultipleInput) {
		this.stringMultipleInput = stringMultipleInput;
	}

	public java.lang.String getStringTextArea() {
		return this.stringTextArea;
	}

	public void setStringTextArea(java.lang.String stringTextArea) {
		this.stringTextArea = stringTextArea;
	}

	public java.lang.Integer getIntegerRadioGroup() {
		return this.integerRadioGroup;
	}

	public void setIntegerRadioGroup(java.lang.Integer integerRadioGroup) {
		this.integerRadioGroup = integerRadioGroup;
	}

	public java.lang.String getStringListBox() {
		return this.stringListBox;
	}

	public void setStringListBox(java.lang.String stringListBox) {
		this.stringListBox = stringListBox;
	}

	public java.lang.Double getDoubleSlider() {
		return this.doubleSlider;
	}

	public void setDoubleSlider(java.lang.Double doubleSlider) {
		this.doubleSlider = doubleSlider;
	}

	public java.lang.Double getDoubleDecimalBox() {
		return this.doubleDecimalBox;
	}

	public void setDoubleDecimalBox(java.lang.Double doubleDecimalBox) {
		this.doubleDecimalBox = doubleDecimalBox;
	}

	public java.lang.Boolean getBooleanCheckBox() {
		return this.booleanCheckBox;
	}

	public void setBooleanCheckBox(java.lang.Boolean booleanCheckBox) {
		this.booleanCheckBox = booleanCheckBox;
	}

	public java.util.Date getDateDatePicker() {
		return this.dateDatePicker;
	}

	public void setDateDatePicker(java.util.Date dateDatePicker) {
		this.dateDatePicker = dateDatePicker;
	}

	public NestedDataObject(java.lang.String stringTextBox, int intIntegerBox,
			java.util.List<java.lang.String> stringMultipleSelector,
			java.util.List<java.lang.String> stringMultipleInput,
			java.lang.String stringTextArea,
			java.lang.Integer integerRadioGroup,
			java.lang.String stringListBox, java.lang.Double doubleSlider,
			java.lang.Double doubleDecimalBox,
			java.lang.Boolean booleanCheckBox, java.util.Date dateDatePicker) {
		this.stringTextBox = stringTextBox;
		this.intIntegerBox = intIntegerBox;
		this.stringMultipleSelector = stringMultipleSelector;
		this.stringMultipleInput = stringMultipleInput;
		this.stringTextArea = stringTextArea;
		this.integerRadioGroup = integerRadioGroup;
		this.stringListBox = stringListBox;
		this.doubleSlider = doubleSlider;
		this.doubleDecimalBox = doubleDecimalBox;
		this.booleanCheckBox = booleanCheckBox;
		this.dateDatePicker = dateDatePicker;
	}

}